spring:
  application:
    name: CineSphere

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/cinesphere
    username: postgres
    password: varlennnn

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  flyway:
       enabled: true
       baseline-on-migrate: true
       schemas: public
       locations: classpath:db/migration
       spring.flyway.out-of-order: true
 

  cinesphere:
   security:
    secret:"palavra_secreta"
